### ISSUE TITLE
Not working for me together with Quafzi's plugin

### ISSUE THREAD

**Issue by wigman** [sdinteractive/SomethingDigital_RecentlyViewed#1]
I'm confused. The readme states this should be used in conjunction with Quafzi_PerformanceTweaks.
BUT, your plugin seems to depend on the default recently viewed function which is disabled by these event overrides in Quafzi's config:

```
  <controller_action_predispatch>
    <observers>
      <log>
        <type>disabled</type>
      </log>
    </observers>
  </controller_action_predispatch>
  <controller_action_postdispatch>
    <observers>
      <log>
        <type>disabled</type>
      </log>
    </observers>
  </controller_action_postdispatch>

  <catalog_controller_product_view>
    <observers>
      <reports>
        <type>disabled</type>
      </reports>
    </observers>
  </catalog_controller_product_view>
```

When I uncomment these three, your module works. Otherwise: no banana's.

The whole point was to disable the log-writes because it crashes my server once in a while.

Am I totally missing something related to a plugin I've installed, or did I misunderstand the functionalities of this module?

Thanks!

**Comment by philwinkle** [comment]
Great, yes, sorry. This needs to be updated with the final version which removed the requirement.

Apologies and thanks. Will get right on this.

On Jul 8, 2015 10:57 AM, Willem Wigman notifications@github.com wrote:

I'm confused. The readme states this should be used in conjunction with Quafzi_PerformanceTweaks.
BUT, your plugin seems to depend on the default recently viewed function which is disabled by these event overrides in Quafzi's config:

  <controller_action_predispatch>
    <observers>
      <log>
        <type>disabled</type>
      </log>
    </observers>
  </controller_action_predispatch>
  <controller_action_postdispatch>
    <observers>
      <log>
        <type>disabled</type>
      </log>
    </observers>
  </controller_action_postdispatch>

  <catalog_controller_product_view>
    <observers>
      <reports>
        <type>disabled</type>
      </reports>
    </observers>
  </catalog_controller_product_view>

When I uncomment these three, your module works. Otherwise: no banana's.

The whole point was to disable the log-writes because it crashes my server once in a while.

Am I totally missing something related to a plugin I've installed, or did I misunderstand the functionalities of this module?

Thanks!

**Comment by wigman** [comment]
Okay, great! Thanks:)

**Comment by wigman** [comment]
Dit you manage to make any progress on this yesterday? :)

**Comment by philwinkle** [comment]
Getting eyes on this today. Sorry for the delay!

**Comment by philwinkle** [comment]
@wigman Please re-test. This should be good to go.

**Comment by wigman** [comment]
Okay, thanks!

**Comment by wigman** [comment]
It works. Thanks a lot!
